(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var c,m="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},n;if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var q={g:!0},r={};try{r.__proto__=q;p=r.g;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var t=n,u=function(a,b){a.prototype=m(b.prototype);a.prototype.constructor=a;if(t)t(a,b);else for(var d in b)if("prototype"!=d)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}else a[d]=b[d]},v=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");
},w=v(this);var x=function(a){a=parseInt(a.getAttribute("slices"),10);isNaN(a)&&(a=5);return a},y=function(a){return a.hasAttribute("direction")?a.getAttribute("direction"):"lefttoright"};var A=function(a){if(!a.gwdIsLoaded()){var b=z(a);b?b.gwdIsLoaded()&&a.gwdLoad():a.gwdLoad()}},B=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},z=function(a){if(B(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&B(a))return a;return null};var C=function(){var a=HTMLElement.call(this)||this;a.a=null;a.frameWidth=0;a.frameHeight=0;return a};u(C,HTMLElement);c=C.prototype;c.connectedCallback=function(){A(this)};c.gwdLoad=function(){var a=this.parentElement.querySelector("canvas");a&&(this.a=a.getContext("2d"),this.frameWidth=parseInt(a.style.width,10),this.frameHeight=parseInt(a.style.height,10));var b=void 0===b?null:b;a=document.createEvent("CustomEvent");a.initCustomEvent("ready",!0,!0,b);this.dispatchEvent(a)};c.gwdIsLoaded=function(){return!!this.a};
c.renderAnimation=function(){};c.getSupportedSwipeDirection=function(){if("undefined"==typeof this.direction)return[0,0];switch(this.direction){case "lefttoright":return[1,0];case "righttoleft":return[-1,0];case "toptobottom":return[0,1];case "bottomtotop":return[0,-1];default:return[0,0]}};c.setDirection=function(){};c.resetDirection=function(){};var D=["direction","slices","transparentbackground"],E=function(){return C.call(this)||this};u(E,C);c=E.prototype;c.connectedCallback=function(){this.c=y(this);this.f=this.hasAttribute("transparentbackground");this.b=x(this);A(this)};c.attributeChangedCallback=function(a){switch(a){case "direction":this.c=y(this);break;case "transparentbackground":this.f=this.hasAttribute("transparentbackground");break;case "slices":this.b=x(this)}};c.setDirection=function(a){this.c=a};
c.resetDirection=function(){this.c=y(this)};
c.renderAnimation=function(a,b,d){this.a.clearRect(0,0,this.frameWidth,this.frameHeight);this.f||this.a.drawImage(a,0,0,this.frameWidth,this.frameHeight);this.a.save();switch(this.c){case "toptobottom":case "bottomtotop":var f=Math.ceil(this.frameWidth/this.b),k=Math.ceil(b.width/this.b);a=f;var l=this.frameHeight;for(var e=0;e<this.b;e++){var g=Math.max(0,Math.min(2*d-(e+1)/this.b,1));var h=f*e;g="toptobottom"==this.c?(g-1)*this.frameHeight:(1-g)*this.frameHeight;this.f||this.a.clearRect(h,g,a,l);
this.a.drawImage(b,k*e,0,k,b.height,h,g,a,l)}break;default:for(f=Math.ceil(this.frameHeight/this.b),k=Math.ceil(b.height/this.b),a=this.frameWidth,l=f,e=0;e<this.b;e++)h=Math.max(0,Math.min(2*d-(e+1)/this.b,1)),h="lefttoright"==this.c?(h-1)*this.frameWidth:(1-h)*this.frameWidth,g=f*e,this.f||this.a.clearRect(h,g,a,l),this.a.drawImage(b,0,k*e,b.width,k,h,g,a,l)}this.a.restore()};w.Object.defineProperties(E,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return D}}});
customElements.define("gwd-slice",E);}).call(this);
